Implementation of extended DSHOT telemetry, smooth temperature limiti…
bird-sanctuary/bluejay pull request #11
Opened 2022-09-07 21:33 UTC by damosvil

…ng function and wdt (currently disabled)

2022-09-07 21:51 UTC, stylesuxx commented
Alright, to we have a lot of stuff going on in this PR:
1. Extended Dshot Telemetry
2. Watchdog implementation - disabled by default, can only be enabled via code
3. Improved handling of temperature

There are a lot of lines where only indentation has changed this pollutes the PR a little bit.
Looking at it, I am not sure if it wouldn't make sense to split it in 3 PRs so it is easier digestible...

I added some comments for the stuff that quickly caught my eye. I will get into the logic with a fresh mind tomorrow.

2022-09-08 09:31 UTC, saidinesh5 commented
Also we have to test watchdog implementation with the longest melody:
```
a,b,c,d,(255,255)*62
```
and make sure it doesn't cause boot loop because we disable all interrupts

2022-09-08 18:04 UTC, damosvil commented
@saidinesh5 In principle WDT implementation is there but disabled by default. I have been playing with it for some time, but I found that at least 0.8ms is not enough for all motor types, so that sometimes it causes the esc to reboot, at least in the workbench. After keeping my drones armed for 5 minutes in my workbech, and being sure that no esc reboot I have flown them with no issues, but it takes extra time testing the drone. 
Please, let me know if you think it is better to remove all the code related to WDT from this pr.

2022-09-10 11:33 UTC, saidinesh5 commented
Yeah watchdog related code should be under a separate PR anyway because it isn't related to extended dshot anyway. Similarly smooth temperature limitation. 

Also, what about beacon melodies? ( The other PR that is currently pending).

2022-09-10 12:20 UTC, stylesuxx commented
> Also, what about beacon melodies? ( The other PR that is currently pending).

EDT is currently the most important thing since those changes is also what the [documentation](https://github.com/bird-sanctuary/bluejay-documentation) is based on. Once EDT is merged, we are on par with documentation and can then merge the other stuff step by step.

I created [Milestones](https://github.com/bird-sanctuary/bluejay/milestones) - would just like to move the discussion to either Discord or the accompanying ticket to not pollute this PR.

2022-09-10 17:38 UTC, damosvil commented
@saidinesh5 Agreed, so I removed all WDT related code.

2022-09-17 11:41 UTC, howels commented
FYI betaflight merged extended dshot telemetry so now would be a good time to add a release or pre-release to esc-configurator for people to test with.

2022-09-17 15:14 UTC, stylesuxx commented
> FYI betaflight merged extended dshot telemetry so now would be a good time to add a release or pre-release to esc-configurator for people to test with.

I will add a pre-release once we have things cleaned up here and finished internal testing.

2022-09-18 19:11 UTC, stylesuxx requested changes

2022-09-18 21:29 UTC, damosvil commented on Bluejay.asm
> +DEFAULT_PGM_ENABLE_TEMP_PROT		EQU	1	; 0=Disabled	1=80C	2=90C	3=100C	4=110C	5=120C	6=130C	7=140C
Fixed

2022-09-18 21:29 UTC, damosvil commented on Bluejay.asm
> +PWM_CENTERED					EQU		DEADTIME > 0			; Use center aligned pwm on ESCs with dead time
Fixed

2022-09-18 21:29 UTC, damosvil commented on Bluejay.asm
> +Pwm_Limit:					DS	1	; Maximum allowed pwm (8-bit)
Fixed

2022-09-18 21:30 UTC, damosvil commented on Bluejay.asm
> +Temp_Pwm_Level_Setpoint:	DS	1	; PWM level setpoint
Fixed

2022-09-18 21:30 UTC, damosvil commented on Bluejay.asm
> +	Wdt_Kick_Enable						; Kick watchdog
WDT code removed in last commit

2022-09-18 21:30 UTC, damosvil commented on Bluejay.asm
> +	orl	EIE1, #80h					; Enable Timer3 interrupts
Fixed

2022-09-18 21:30 UTC, damosvil commented on Bluejay.asm
> +	setb	IE_EA				; Enable interrupts again
Fixed

2022-09-18 21:31 UTC, damosvil commented on Bluejay.asm
> +	call	switch_power_off		; Switch power off again, after initializing ports
Fixed

2022-09-18 21:31 UTC, damosvil commented on Bluejay.asm
> +	call	led_control			; Set LEDs to programmed values
Fixed

2022-09-18 21:31 UTC, damosvil commented on Bluejay.asm
> +	mov	EIE1, #80h					; Enable Timer3 interrupts
Fixed

2022-09-18 21:31 UTC, damosvil commented on Bluejay.asm
> +	clr	IE_EA						; Disable interrupts
Fixed

2022-09-18 21:31 UTC, damosvil commented on Bluejay.asm
> +	; Disable wdt and wait before posibly reenable shortly again
WDT code removed from last commit

2022-09-18 21:32 UTC, damosvil commented on Layouts/Base.inc
> +TEMP_LIMIT		EQU	49				; Temperature measurement ADC value for which main motor power is limited at 80degC (low byte, assuming high byte is 1)
Fixed

2022-09-18 21:32 UTC, damosvil commented on Layouts/Base.inc
> +TEMP_LIMIT_STEP	EQU	9				; Temperature measurement ADC value increment for another 10degC
Fixed

2022-09-18 21:32 UTC, damosvil commented on Bluejay.asm
> +Flag_Had_Signal				BIT	Flags3.2		; Used to detect reset after having had a valid signal
Fixed

2022-09-18 21:32 UTC, damosvil commented on Bluejay.asm
> +	mov Ext_Telemetry_H, #0				; Clear extended telemetry data
Fixed

2022-09-18 21:32 UTC, damosvil commented on Common.inc
> +	mov WDTCN,#0 					; Set WDT interval to 0,8 ms
WDT code removed in last commit

2022-09-18 21:32 UTC, damosvil commented on Common.inc
> +	mov WDTCN,#0A5h					; reset watchdog timer
WDT code removed in last commit

2022-09-18 21:32 UTC, damosvil commented on Common.inc
> +	mov WDTCN,#0DEh					; disable software watchdog timer
WDT code removed in last commit

2022-09-18 21:33 UTC, damosvil commented on Bluejay.asm
> +;Flag_Clock_At_48MHz			BIT	Flags2.4		; Set if 48MHz MCUs run at 48MHz
No longer used

2022-09-19 22:28 UTC, stylesuxx commented
**ATTENTION**: This PR continues in #20 

There were some issues with the PR, switching from old repo to detached repo and thus @damosvil made a new PR (with feedback from here - at least partially - applied). I'll leave this open since it has been referenced in other issues and close it once we finish the NEW PR #20

2022-10-04 23:34 UTC, stylesuxx commented
Closing this since superseding #20 is merged.

2022-10-04 23:34 UTC, closed without merging