Removed dithering feature
bird-sanctuary/bluejay pull request #181
Opened 2023-10-24 16:36 UTC by damosvil

Removed dithering feature because it is only 1 bit dithering, it updates when dshot frames are received (not every pwm cycle) and overall gyro noise always overlaps the dithering value injected when the dshot frame is received

2023-10-24 23:58 UTC, stylesuxx requested changes

2023-10-24 23:58 UTC, stylesuxx commented on src/Modules/Settings.asm
> +    ; Return
Indentation is off.

2023-10-26 16:12 UTC, damosvil commented on src/Modules/Settings.asm
> +    ; Return
Fixed

2023-10-28 03:00 UTC, hyp0dermik-code approved these changes
Tested OK, LA file for reference
[virt000_armed_8per_0211rc2_remdither.zip](https://github.com/bird-sanctuary/bluejay/files/13194272/virt000_armed_8per_0211rc2_remdither.zip)

2023-10-28 14:02 UTC, stylesuxx approved these changes

2023-10-28 14:05 UTC, merged