Fix/prevent damp power inversion
bird-sanctuary/bluejay pull request #76
Opened 2023-03-03 17:13 UTC by damosvil

Set Flag_Rcp_Stop if it rcpulse is less or equal to deadtime,
so damp register is always triggered before power register

2023-03-03 17:24 UTC, Burdalfis reviewed
Looks good, can test in a few hours if need be.

2023-03-03 17:29 UTC, damosvil commented
I tested it on my side, but please, when possible could you make it a 5min smoke test?

2023-03-03 19:28 UTC, stylesuxx requested changes
Could you explain the current behavior and consequences of this change? Looking at the code I would assume that RCP stop flag has never been set unless running on a "0" deadtime MCU?

If this is the case are we sure, that whatever is executed in the code path that is now triggered is properly working? Or is it currently being executed in different cases too?

Also you tagged this as "enhancement" - this rather seems like a fix to me. I know, it's only semantics - just wanted to double check.

2023-03-03 19:28 UTC, stylesuxx commented on Bluejay.asm
> +	mov	A, Temp4
One space too much ;-)

2023-03-03 22:04 UTC, damosvil commented on Bluejay.asm
> +	mov	A, Temp4
fixed

2023-03-03 22:53 UTC, damosvil commented
> Could you explain the current behavior and consequences of this change? Looking at the code I would assume that RCP stop flag has never been set unless running on a "0" deadtime MCU?

Yes, previously rcp stop was set only when rcp was 0.

This change will set rc pulse to 0 always it is smaller than deadtime + 1, because this way damp register is set to deadtime and power register is always bigger than damp register.
Remember that when PCA counter overflows and is set to 0 channel output is set to 0, then when counter reaches damp value channel output is inverted and set to 1, and when counter reaches power value channel output is inverted again and is set to 0.
When 0 deadtime rcp stop will be set when pwm is less that 1, because I added 1 unit to DEADTIME.
 
> If this is the case are we sure, that whatever is executed in the code path that is now triggered is properly working? Or is it currently being executed in different cases too?

It sets rcpulse to 0 in all cases

> Also you tagged this as "enhancement" - this rather seems like a fix to me. I know, it's only semantics - just wanted to double check.

Changed to fix

2023-03-04 21:04 UTC, stylesuxx approved these changes

2023-03-12 18:19 UTC, damosvil commented
I am canceling this pr because pca doesn't work the way I figured out. This pr is doesn't fix any issue

2023-03-12 18:19 UTC, closed without merging